sonata_admin:
    title: SCHK Pardubice
#    title_logo: images/logo.jpg
    options:
        html5_validate: true
    templates:
        layout: AppBundle::admin/standard_layout.html.twig
#        list: AdminBundle:CRUD:base_list.html.twig
#        user_block: SonataUserBundle:Admin/Core:user_block.html.twig
    dashboard:
#        blocks:
#            -
#                position: right
#                type: admin.block.orders
#            -
#                position: left
#                type: admin.block.contacts
#            -
#                position: right
#                type: admin.block.users
#            -
#                position: left
#                type: admin.block.ratings
#            -
#                position: left
#                type: admin.block.phone_calls
        groups:
            admin.group.pages:
                label: CMS
                label_catalogue: AdminBundle
                icon: '<i class="fa fa-sitemap"></i>'
                items:
                    - admin.page
                    - admin.event
                roles:
                    - ROLE_ADMIN

            admin.group.blog:
                label: Blog
                label_catalogue: ~
                icon: '<i class="fa fa-newspaper-o"></i>'
                items:
                    - admin.post
                    - admin.comment
                roles:
                    - ROLE_ADMIN

            admin.group.classification:
                label: Classification
                label_catalogue: ~
                icon: '<i class="fa fa-tags"></i>'
                items:
                    - admin.category
                    - admin.collection
                    - admin.tag
                    - admin.context
                roles:
                    - ROLE_ADMIN

            admin.group.media:
                label: Media
                label_catalogue: ~
                icon: '<i class="fa fa-image"></i>'
                items:
                    - admin.media
                    - admin.gallery
                roles:
                    - ROLE_ADMIN

            admin.group.user:
                label: Users
                label_catalogue: ~
                icon: '<i class="fa fa-users"></i>'
                items:
                    - admin.user
#                    - admin.group
                roles:
                    - ROLE_ADMIN